/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stopwatch;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;

/**
 *
 * @author shubh
 */
public class stopwatchfrm extends javax.swing.JFrame {

    /**
     * Creates new form stopwatchfrm
     */
    static int posX;
    static int posY;
    static int h = 00;
    static int m = 00;
    static int s = 00;
    static int millis = 00;
    static boolean check = true;

    public stopwatchfrm() {
        initComponents();
        myinitComponents();
        //start.setBorder(new RoundedBorder(3));
        //pause.setBorder(new RoundedBorder(3));
        //close.setBorder(new RoundedBorder(3));
        //reset.setBorder(new RoundedBorder(3));
        // start.setBackground(Color.GRAY);
        start.setForeground(Color.white);
        // pause.setBackground(Color.GRAY);
        pause.setForeground(Color.white);
        ///reset.setBackground(Color.GRAY);
        reset.setForeground(Color.white);
        close.setBackground(new Color(150, 30, 30));
        close.setForeground(Color.white);
        //jPanel1.setSize(498, 285);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        start = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        close = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        mm = new javax.swing.JLabel();
        hh = new javax.swing.JLabel();
        ss = new javax.swing.JLabel();
        milllis = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(":");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stopwatch");
        setBackground(new java.awt.Color(60, 63, 65));
        setMaximumSize(new java.awt.Dimension(498, 280));
        setMinimumSize(new java.awt.Dimension(498, 280));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(498, 280));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(60, 63, 65));
        jPanel1.setMaximumSize(new java.awt.Dimension(498, 285));
        jPanel1.setMinimumSize(new java.awt.Dimension(498, 280));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        start.setBackground(new java.awt.Color(60, 63, 65));
        start.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        pause.setBackground(new java.awt.Color(60, 63, 65));
        pause.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pause.setText("Pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        close.setBackground(new java.awt.Color(60, 63, 65));
        close.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        close.setForeground(new java.awt.Color(255, 0, 51));
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(60, 63, 65));
        reset.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        mm.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        mm.setForeground(new java.awt.Color(255, 255, 255));
        mm.setText("00");

        hh.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        hh.setForeground(new java.awt.Color(255, 255, 255));
        hh.setText("00");

        ss.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        ss.setForeground(new java.awt.Color(255, 255, 255));
        ss.setText("00");

        milllis.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        milllis.setForeground(new java.awt.Color(255, 255, 255));
        milllis.setText("00");

        b2.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText(":");

        b1.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText(":");

        b3.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText(".");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stopwatch/icons8_stopwatch_30px.png"))); // NOI18N

        jTextField1.setForeground(new java.awt.Color(60, 63, 65));
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("hh");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("mm");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ss");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(hh)
                .addGap(2, 2, 2)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(mm)
                .addGap(4, 4, 4)
                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(ss)
                .addGap(5, 5, 5)
                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(milllis))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2)))
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hh, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(milllis, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reset)
                    .addComponent(start)
                    .addComponent(pause)
                    .addComponent(close)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static class RoundedBorder implements Border {

        private int radius;

        RoundedBorder(int radius) {
            this.radius = radius;
        }

        public Insets getBorderInsets(Component c) {
            return new Insets(this.radius + 1, this.radius + 1, this.radius + 2, this.radius);
        }

        public boolean isBorderOpaque() {
            return true;
        }

        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
        }
    }

    private void myinitComponents() {

        start.setText("Start");
        pause.setText("Pause");
        close.setText("Close");
        reset.setText("Reset");
        milllis.setText("00");
        ss.setText("00");
        mm.setText("00");
        hh.setText("00");
        millis = 0;
        s = 0;
        m = 0;
        h = 0;
        check = false;
    }

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        // TODO add your handling code here:
        if ("Pause".equals(pause.getText())) {
            if (!(millis == 0 && s == 0 && m == 0 && h == 0) && check == true) {
                check = false;
                pause.setText("Resume");
            }

        } else if ("Resume".equals(pause.getText())) {

            if (!(millis == 0 && s == 0 && m == 0 && h == 0)) {
                start.setText("Start");
                pause.setText("Pause");
                startActionPerformed(evt);
            }

        }
    }//GEN-LAST:event_pauseActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed

        check = true;
        if ("Start".equals(start.getText())) {
            Thread t = new Thread() {
                public void run() {
                    start.setText("Stop");
                    for (;;) {
                        if (check == true) {
                            try {

                                if (millis > 99) {
                                    millis = 0;
                                    s++;

                                }
                                if (s > 60) {
                                    millis = 0;
                                    s = 1;
                                    m++;

                                }
                                if (m > 60) {
                                    millis = 0;
                                    m = 1;
                                    s = 1;
                                    h++;
                                }
                                if (String.valueOf(millis).length() == 1) {
                                    milllis.setText("0" + String.valueOf(millis));
                                } else {
                                    milllis.setText(String.valueOf(millis));
                                }

                                if (String.valueOf(s).length() == 1) {
                                    ss.setText("0" + String.valueOf(s));
                                } else {
                                    ss.setText(String.valueOf(s));
                                }

                                if (String.valueOf(m).length() == 1) {
                                    mm.setText("0" + String.valueOf(m));
                                } else {
                                    mm.setText(String.valueOf(m));
                                }

                                if (String.valueOf(h).length() == 1) {
                                    hh.setText("0" + String.valueOf(h));
                                } else {
                                    hh.setText(String.valueOf(h));
                                }

                                sleep(9);
                                millis++;

                            } catch (InterruptedException e) {
                                JOptionPane.showMessageDialog(null, "Error");
                            }
                        } else {
                            break;
                        }
                    }

                }
            };
            t.start();
        } else if ("Stop".equals(start.getText())) {
            myinitComponents();
        }


    }//GEN-LAST:event_startActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        myinitComponents();
    }//GEN-LAST:event_resetActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
          //initialiseGUI(rootPane);
        
    }//GEN-LAST:event_formMouseDragged

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        //initialiseGUI(jPanel1);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void initialiseGUI(Component component){
    //<editor-fold defaultstate="collapsed" desc="code">
    component.addMouseListener(new MouseAdapter() {
        public void mousePressed(MouseEvent e) {
            posX = e.getX();
            posY = e.getY();
        }
    });

    component.addMouseMotionListener(new MouseAdapter() {
        public void mouseDragged(MouseEvent evt) {
            //sets frame position when mouse dragged            
            Rectangle rectangle = getBounds();
            jPanel1.setBounds(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY, rectangle.width, rectangle.height);
        }

        private Object getGUI() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    });
    //</editor-fold>
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Set cross-platform Java L&F (also called "Metal")
            UIManager.setLookAndFeel(
                    UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }

        new SwingApplication(); //Create and show the GUI.

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stopwatchfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JButton close;
    private javax.swing.JLabel hh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel milllis;
    private javax.swing.JLabel mm;
    private javax.swing.JButton pause;
    private javax.swing.JButton reset;
    private javax.swing.JLabel ss;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
